- apiVersion: v1
  kind: Namespace
  metadata:
    name: default-1679932767554
  spec:
    finalizers:
      - kubernetes
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: mdservice10
    namespace: default-1679932767554
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: mdservice10
    template:
      metadata:
        labels:
          app: mdservice10
      spec:
        nodeSelector:
          kubernetes.io/os: linux
        containers:
          - name: mdservice10
            image: k8workshopregistry.azurecr.io/mdservice1.0:latest
            ports:
              - containerPort: 80
            resources:
              requests:
                cpu: '2'
                memory: 512M
              limits:
                cpu: '256'
                memory: 11400G
- apiVersion: v1
  kind: Service
  metadata:
    name: mdservice10-service
    namespace: default-1679932767554
  spec:
    type: LoadBalancer
    ports:
      - targetPort: 80
        name: port80
        port: 80
        protocol: TCP
    selector:
      app: mdservice10
